server:
  port: 8081

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification-service/**
          filters:
            - StripPrefix=1

        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/category-service/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: http://product-service:8083
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart-service/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              # Local development origins
              - "http://localhost"
              - "http://localhost:80"
              - "http://localhost:5173"
              # Production origins (HTTP and HTTPS)
              - "http://18.217.148.69"
              - "http://18.217.148.69:80"
              - "http://18.217.148.69:8080"
              - "http://18.217.148.69:5173"
              - "https://18.217.148.69"
              - "https://18.217.148.69:443"
              - "https://18.217.148.69:8080"
              - "https://18.217.148.69:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600


eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
    region: default
    availability-zones:
      default: default
    use-dns-for-fetching-service-urls: false
    eureka-server-d-n-s-name: service-registry
    eureka-server-port: 8761
  instance:
    prefer-ip-address: true
    hostname: api-gateway
    appname: api-gateway
