spring:
    application:
        name: auth-service
  ## MongoDB Properties - use docker to host mongodb container for connecting like this
    data:
      mongodb:
        database: purely_auth_service
        port: 27017
        host: localhost
        #authentication-database: admin
        #username: rootuser
        #password: rootpass        
        #auto-index-creation: true
server:
    port: 9030

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost