spring:
    application:
        name: auth-service
  ## MongoDB Properties - use docker to host mongodb container for connecting like this
    data:
      mongodb:
        uri: mongodb://admin:password@mongodb:27017/purely_auth_service?authSource=admin
server:
    port: 8081

eureka:
    client:
        serviceUrl:
            defaultZone: http://172.31.26.143:8761/eureka/
    instance:
        hostname: 172.31.26.143
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true