global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Service Registry
  - job_name: 'service-registry'
    static_configs:
      - targets: ['service-registry:8761']
    metrics_path: '/actuator/prometheus'

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8081']
    metrics_path: '/actuator/prometheus'

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080']
    metrics_path: '/actuator/prometheus'

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']
    metrics_path: '/actuator/prometheus'

  # Product Service
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8080']
    metrics_path: '/actuator/prometheus'

  # Category Service
  - job_name: 'category-service'
    static_configs:
      - targets: ['category-service:8080']
    metrics_path: '/actuator/prometheus'

  # Cart Service
  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:8080']
    metrics_path: '/actuator/prometheus'

  # Order Service
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8080']
    metrics_path: '/actuator/prometheus'

  # Notification Service
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8080']
    metrics_path: '/actuator/prometheus'

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Blackbox Exporter
  - job_name: 'blackbox-exporter'
    static_configs:
      - targets: ['blackbox-exporter:9115']

  # Frontend Health Check
  - job_name: 'frontend-health'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/health'
    scrape_interval: 30s

  # API Gateway Health Check
  - job_name: 'api-gateway-health'
    static_configs:
      - targets: ['api-gateway:8081']
    metrics_path: '/actuator/health'
    scrape_interval: 30s

  # MongoDB (if you have MongoDB exporter)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s 