spring:
    application:
        name: cart-service
    data:
        mongodb:
            database: purely_cart_service
            port: 27017
            host: localhost
            #authentication-database: admin
            #username: rootuser
            #password: rootpass        
            #auto-index-creation: true            
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9060

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost