spring:
    application:
        name: category-service
        
    data:
        mongodb:
            database: purely_category_service
            port: 27017
            host: localhost
            #authentication-database: admin
            #username: rootuser
            #password: rootpass        
            #auto-index-creation: true              
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9000

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost