spring:
    application:
        name: order-service

    data:
        mongodb:
            uri: mongodb://admin:password@mongodb:27017/purely_order_service?authSource=admin

    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 8085

eureka:
    client:
        serviceUrl:
            defaultZone: http://172.31.26.143:8761/eureka/
    instance:
        hostname: 172.31.26.143
        prefer-ip-address: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        prometheus:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true