groups:
  - name: purely_blackbox
    rules:
      # HTTP endpoint monitoring
      - alert: EndpointDown
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Endpoint {{ $labels.instance }} is down"
          description: "Endpoint {{ $labels.instance }} has been down for more than 1 minute."

      # High response time alert
      - alert: HighResponseTime
        expr: probe_duration_seconds > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time for {{ $labels.instance }}"
          description: "Response time for {{ $labels.instance }} is above 2 seconds for more than 5 minutes."

      # SSL certificate expiration
      - alert: SSLCertExpiringSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate expiring soon for {{ $labels.instance }}"
          description: "SSL certificate for {{ $labels.instance }} will expire in less than 30 days."

      # HTTP status code errors
      - alert: HTTPStatusError
        expr: probe_http_status_code >= 400
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "HTTP error for {{ $labels.instance }}"
          description: "HTTP status code {{ $labels.probe_http_status_code }} for {{ $labels.instance }}"

      # Service unavailable
      - alert: ServiceUnavailable
        expr: probe_http_status_code == 503
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Service unavailable: {{ $labels.instance }}"
          description: "Service {{ $labels.instance }} is returning 503 status code."

      # Connection timeout
      - alert: ConnectionTimeout
        expr: probe_duration_seconds > 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Connection timeout for {{ $labels.instance }}"
          description: "Connection to {{ $labels.instance }} is timing out (over 10 seconds)." 