spring:
    application:
        name: product-service
    data:
        mongodb:
            uri: mongodb://admin:password@mongodb:27017/purely_product_service?authSource=admin
            #authentication-database: admin
            #username: rootuser
            #password: rootpass        
            #auto-index-creation: true            
            
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 8083

eureka:
    client:
        serviceUrl:
            defaultZone: http://service-registry:8761/eureka/
    instance:
        prefer-ip-address: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        prometheus:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true