spring:
    application:
        name: product-service
    data:
        mongodb:
            host: localhost
            port: 27017
            database: purely_product_service
            #authentication-database: admin
            #username: rootuser
            #password: rootpass        
            #auto-index-creation: true            
            
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9010

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost